### PR TITLE
Implement Dark Mode

### PR DESCRIPTION
**Pull request by majo0112**
## Description

I implemented a dark mode feature. Users can now toggle between light and dark themes to enhance their viewing experience. I also made several improvements to the dark theme's design, ensuring a visually appealing and user-friendly interface. Additionally, I added a dark mode toggle button for easy accessibility. This enhancement provides users with a more comfortable browsing experience in low-light environments and adds a modern and customizable touch to our UI.

https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/106662964/ed1efde9-f63b-4de1-8bcb-98bc1706a574

### CODE REVIEW

**Comment by SannitaSSJ** [comment]
This is extremely useful! Please, first fix the conflict with the current version.

**Comment by majo0112** [comment]
@SannitaSSJ The conflict has been fixed. 

https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/106662964/4961a3c5-6715-49ef-8d20-4ce8055f4328

**Comment by samuelalison** [comment]
Nice work @majo0112

**Review by fernandouval — CHANGES_REQUESTED** [review]
I think this can be achieved just by adding a class to the body (ie: 'dark-mode') and changing .dark-mode .<class-to-change> in the dark-mode.css accordingly. Also .dark-mode <button> can be shown or hidden by the class (for the selectors). In that way the only JS code should be to toggle that class.

**Comment by majo0112** [comment]
I've made the requested changes. @fernandouval

**Comment by majo0112** [comment]
@SannitaSSJ @fernandouval @EneHacheCe @wikicurricula-uy 

I made the following changes: I added dark mode to 'ghana.html' and applied it to the SVGs.

img-wiki

**Pull request merged**
