### PR TITLE
Scripting to automate fetching of articles from wikidata api and analysing the articles

### LINKED ISSUE #52: Scripting to automate fetching of articles from wikidata api and analysing the articles
Based on the general video meeting that was held and @EneHacheCe  view on automating the querying and analysis of data by running a script. 
A script that automates running all the processes should be created and it should accept the parameter "language"
which was stated in issue #11. Solving issue #11 will be a great input to solving this issue, as well as a notable input to solving;
"Implement - and deploy at Toolforge - Wikicurricula for Ghana's national curriculum, with reference to the English Wikipedia."

### PR DESCRIPTION
**Pull request by Bhbee**
This PR attempts to implement the solutions discovered on PR #50, doing research on fetching article data. I created a SUPERBOT(super_bot.py).

The  script implements multiprocessing for parallel execution of subprocesses( use of multiple processes or threads to perform tasks concurrently, taking advantage of the capabilities of multi-core processors )

The multiprocessing pool consists of four processes which are:
- query.py: To fetch the article data from Wikidata, and an "article_name.csv" and update the "subjects.csv" file
- bot.py: To perform analysis on the data(article_name.csv) and generate a result.txt
- translate.py: To reorganize the result.txt into a "voci_2023.tsv" file

This fixes #52

### CODE REVIEW

**Comment by Bhbee** [comment]
@GonzaFP
This is the PR I made for automating the "fetching of data by making an API call",  "Analysing the article with bot.py" and "running the translate.py to generate the voci_2023.tsv".

You can check PR #46 to understand the process from scratch.

I'm currently awaiting reviews from our mentors but this is my thought  process in code.

**Comment by wikicurricula-uy** [comment]
I'll wait for https://github.com/wikicurricula-uy/wikicurricula-boilerplate/pull/46 to be merged before reviewing this one

**Comment by Bhbee** [comment]
> I'll wait for #46 to be merged before reviewing this one

Alright

**Comment by wikicurricula-uy** [comment]
Hey, @Bhbee ! I'm seeing too many changes 
imagen
It looks like your changes are compared to a previous version, even though I've merged #46 already (I don't know why it works like this, I have to research).
Let's close this pull request and please make another one with the same changes. Thanks!

**Comment by Bhbee** [comment]
Alright, I'll resolve the conflicts and make  another PR
yes, I'll have to merge the upstream with the main so the new changes can be applied. I'll solve the conflicts with the main changes. Thank you.

**Pull request closed without merging**
