### PR TITLE
Implement and deploy wikicurricula for ghana at toolforge

### PR DESCRIPTION
**Pull request by Bhbee**
This PR implements Wikicurriculla for Ghana's national curriculum, after automating the fetching of data and parameterizing to make the implementation easier. 

 My preceding PRs before this stage are: #40, #46, #49 and #50

@EneHacheCe @SannitaSSJ   @fernandouval  @wikicurricula-uy  Kindly review for any suggestions and corrections before I move on to deploying to Toolforge

https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/100197825/6aa9819e-1371-4ff8-aa50-6be10fae06c8

### CODE REVIEW

**Comment by Bhbee** [comment]
Hey @SannitaSSJ 

Thank you for your clear review and additions to my files. I've resolved the conflict issues and also commented out the "twi" configuration until you have the chance to help with the correct templates. I've submitted PR #7, which @EneHacheCe  commented on and approved for the templates. I've applied those templates, but I'd appreciate it if @EneHacheCe could kindly review them as well.

I've also corrected "common_gallery" and "common_pages" to "commons_gallery" and "commons_pages," as the project is named Wikimedia Commons.

If there are any further changes I need to make, please let me know in your review.

Thanks again!

**Comment by SannitaSSJ** [comment]
Hey @Bhbee I made some more changes to template config, because some of the templates listed for the other languages were wrong. Please, update `data-gathering/serialize_data.py` accordingly -- I just don't have the time to fix that file too.

I left some of the fields empty since there is no corresponding template in the relevant community. For the time being I'd leave them empty, maybe we can populate them when we find something that is similar.

Sorry for giving you more work, after this we should be good to go finally.

**Comment by Bhbee** [comment]
Hi @SannitaSSJ  It's no problem at all.

Thank you for the updates. I have implemented the required changes in the data-gathering/serialize_data.py as per your instructions. I fully recognize the significance of having precise templates for various languages, and I agree that we can populate them as we come across relevant templates. This aligns with the purpose of creating the serialize_data.py script – to facilitate future updates and maintain accuracy.

**Comment by SannitaSSJ** [comment]
@Bhbee in order to close this PR, I would like you to synchronise your branch with the current version of the main branch, since we made different changes, and your branch would cancel most of them (especially the corrections to readme.md and contribute.md, and the images). After you've done so, please let me know and I'll evaluate what you've done.

**Comment by Bhbee** [comment]
Alright
I will get back to you soon. Thank you

**Comment by Bhbee** [comment]
I've pulled your changes to the language_template_config.json file and I edited bot.py.
I added checking for #RINVIA or #REDIRECT i.e. for redirection for English since the countries are different. 
 if "#RINVIA"  in wikitext or "#REDIRECT" in wikitext:
         #   print (wikitext)

            start = wikitext.find("[[")
            end = wikitext.find("]]", start)
            article2 = wikitext[start + 2:end]
            article2 = article2.strip()
            article2 = article2.replace("_", " ")


I have also modified the query.py file to generate grades of each curriculum so it can be displayed on the pop-ups.
I also implemented my changes at PR #76 of having a single script(super_bot.py) to run all necessary scripts to generate the VOCI files needed by either of the countries' curricula.


https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/100197825/5c2987de-dabc-4a34-8434-de2981c50650

**Comment by Bhbee** [comment]
It's merged 
Thanks @SannitaSSJ

**Pull request merged**
