### PR TITLE
UI fix: Navbar interactivity

### PR DESCRIPTION
**Pull request by MaryannAlonge**
Solved issue #38 by redesigning the nav bars across all 3 visualization pages

https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/89271635/fd9005d8-914e-4fc1-80da-b42f536305b2

### CODE REVIEW

**Comment by MaryannAlonge** [comment]
https://github.com/wikicurricula-uy/wikicurricula-boilerplate/assets/89271635/8072ef63-9713-4e7c-a709-0c97780972c4

**Comment by wikicurricula-uy** [comment]
Hello, @MaryannAlonge ! I'm closing the issue and PR since we will not be using the "Enties with warnings" and "authors and publications" tabs for now. All these tabs should remain hidden for now.

**Comment by MaryannAlonge** [comment]
@wikicurricula-uy @fernandouval @EneHacheCe how about re-opening a new pull request for only the required page since others would be hidden?

**Comment by wikicurricula-uy** [comment]
Hello! But what's the point in improving the navigation tabs is there is only one page? What tabs would you be improving?

**Comment by MaryannAlonge** [comment]
Just the "Wikicurricula and Italian Schools" tab I guess?

**Pull request closed without merging**
