### PR TITLE
Fixed and enabled the feature that counts the templates (avisi) added to an article.

### PR DESCRIPTION
**Pull request by GonzaFP**
Hello @EneHacheCe @fernandouval @SannitaSSJ @wikicurricula-uy , I have fixed the referenced feature.
I noticed that the templates used in the avvisi function were for the italian wikipedia so I changed them to those of the spanish wikipedia and configAvvisi was 0 so I changed it to 1. Then I enabled the feature by changing their values in translate.py and dv1.js.

I look forward to hearing from you.

### CODE REVIEW

**Comment by SannitaSSJ** [comment]
Hey @GonzaFP, I think it works correctly. Please, fix the conflicts with the documentation files, first, and then I'll merge.

**Comment by GonzaFP** [comment]
@SannitaSSJ  Alright thanks

**Comment by GonzaFP** [comment]
@SannitaSSJ I have resolved the conflicts. Thanks

**Comment by GonzaFP** [comment]
Thanks @SannitaSSJ

**Pull request merged**
