### PR TITLE
Translated all the variable names and function names in bot.py to English

### PR DESCRIPTION
**Pull request by GonzaFP**
I have translated all the variable names and function names in bot.py to English. I have also commented what each function does. Let me know if there is any thing I need to change.

### CODE REVIEW

**Comment by wikicurricula-uy** [comment]
Very promising and easy to review! Thanks!
It even works well for the good articles and featured articles flags. 
However, I think I'm spotting an error: I'm not getting the "all visits" value

Steps to reproduce.
1. Replace query.csv with a list of article names from the English Wikipedia, for example:
imagen
2. In your command line, move to the data-gathering folder and run the bot.py script
`python3 bot.py`
3. Change line 31 in translate.py so that it can work with restults.txt instead of resultati.txt
4.  In your command line, run the translate.py script
`python3 translate.py`
5. Open voci_2023.tsv. Notice that the all_visits colums shows only ERROR
imagen

Let me know if you can reproduce the error or not. I think you are very close to getting it right! Please reopen this PR or create a new one when you are ready.

**Comment by GonzaFP** [comment]
Alright let me work on it. Thanks

**Comment by GonzaFP** [comment]
Hello @wikicurricula-uy , I reproduced the error and fixed it. The error was on line 151 in bot.py instead of language, it was lingua. 
Thanks!

**Comment by GonzaFP** [comment]
Hello @wikicurricula-uy  @EneHacheCe, I have fixed my error, it was the visits variable.

**Comment by wikicurricula-uy** [comment]
Ahh... I think this may have to do with differences between how english and panish wikipedia work then. I'll keep explorting the issue and see what i find. in the meantime, if you can perform these tests (or share the results of what you've already tested) i'd appreciate it.

Translated version of bot.py with English Wikipedia -> FAILS
Translated version of bot.py with Spanish Wikipedia -> Works or fails?
Previous version of bot.py with Spanish Wikipedia -> Works or fails?

**Comment by GonzaFP** [comment]
@wikicurricula-uy how can I share the results? Should I take screen shots and post them here?

**Comment by EneHacheCe** [comment]
No, just tell me if it works or if each case works or doesn't work so we
can try to find if the error is here or if it had been introduced before

**Comment by GonzaFP** [comment]
While working with Ghana's curriulum which was English, it worked.
I have also tested it with the spanish version and it worked

**Comment by GonzaFP** [comment]
@wikicurricula-uy @EneHacheCe @SannitaSSJ I have made a new pull request for this issue.

**Pull request closed without merging**
