### PR TITLE
Fixes #15 - Improve design of Credits section

### LINKED ISSUE #15: Improve design of "Credits" section

### PR DESCRIPTION
**Pull request by Urmilasc**
Fixes #15 

Improvement design of Credit/footer section

Updated footer - 
Screenshot 2023-10-06 194855

### CODE REVIEW

**Comment by SannitaSSJ** [comment]
Two things;
* please re-instate Iolanda Pensa as Ideator and responsible of the project -- it has been wrongly removed
* clean up the spaces in the "docentes" part

The rest looks good to me.

**Comment by Urmilasc** [comment]
Hello @SannitaSSJ , I didn't understand what you have written can you please write it in english .

Thank you !!

**Comment by samuelalison** [comment]
> Hello @SannitaSSJ , I didn't understand what you have written,
> 
> please re-instate Iolanda Pensa as Ideator and responsible of the project -- it has been wrongly removed clean up the spaces in the "docentes" part
> 
> can you please write it in english .
> 
> Thank you !!

Hi @Urmilasc  you removed 
"Ideación y responsable
Iolanda Pensa"

Screenshot (33)

**Comment by samuelalison** [comment]
Can we collaborate on this together?

**Comment by Urmilasc** [comment]
Heyy @samuelalison , surely we can collaborate , but how to do that , I don't know ?

**Comment by samuelalison** [comment]
I see you have added the
"Ideación y responsable
Iolanda Pensa" in you new pull request. Let me just work on this to get myself acquainted with the codebase.

**Comment by Urmilasc** [comment]
Yess sure, @samuelalison , you can work on it !!

**Comment by SannitaSSJ** [comment]
> can you please write it in english .

I think I wrote already in English, and next time I would very much appreciate a better tone.

Anyway @samuelalison already clarified what I wanted about Iolanda Pensa: she's the one who had the idea first, so it's only fair to credit her.

Also, in the "docentes" part there are some additional spaces that I would like you to remove near Annabel Castro, Franco Salvetti, Iliana Trejos Cabrera and Marcelo Mónico:
```
									<p  class="mb-1">Ana Miranda </p>
									<p class="mb-1">	Annabel Castro</p>
									<p class="mb-1">Cecilia Torres</p>	
									<p class="mb-1">	Franco Salvetti</p>
									<p class="mb-1">	Iliana Trejos Cabrera</p>
									<p class="mb-1">	Marcelo Mónico</p>
									<p class="mb-1">Paula Olagüe Schettini</p>	
									<p class="mb-1">Romina Smith</p>	
```

**Comment by SannitaSSJ** [comment]
Ok, I see you opened #37 that fixes the removal of Pensa's name, there is still the additional spaces problem.

**Pull request merged**
