### PR TITLE
setting up required accounts

### PR DESCRIPTION
**Pull request by Bhbee**
This PR contributes to a Microtask on WikiCurricula, an interface to represent curriculum data, which is to write documentation on how to deploy Wikicurrícula Boilerplater in Toolforge. I practised migrating Uruguay's Wikicurricula from its hosting (Github Pages) to Toolforge.[Available here](https://tools-static.wmflabs.org/wikicurricula-uy/wikicurricula-boilerplate/visualization/index.html)

**Terminal commands**

terminal

**Deployed on toolforge**

Deployed on toolforge

### CODE REVIEW

**Comment by Bhbee** [comment]
Completed task @EneHacheCe

**Comment by EneHacheCe** [comment]
Hey @Bhbee, DM me through telegram please, I want to make sure I haven't accidentally removed you from the groupchat.

**Comment by EneHacheCe** [comment]
Great, @Bhbee ! Thanks for deploying Uruguay's Wikicurricula in Toolforge.

I'm not sure about having the instructions at a separate md file... Why not have them in the Readme ? @fernandouval , @SannitaSSJ have you got any opinions on this?

**Comment by Bhbee** [comment]
@EneHacheCe , I just sent a message to the group chat. I wasn't removed.
Should I just add the documentation to the readme file?

**Comment by SannitaSSJ** [comment]
I think documentation in a readme will be easier for people to find.

**Comment by Bhbee** [comment]
Alright, I'll move it to the readme.md file

**Comment by Bhbee** [comment]
Moved the documentation on the deployment in Toolforge to the readme.md file

**Comment by wikicurricula-uy** [comment]
thanks!

**Pull request merged**
