### PR TITLE
Updated credit/footer section 

### LINKED ISSUE #15: Improve design of "Credits" section

### PR DESCRIPTION
**Pull request by Urmilasc**
Fixes #21 
Fixes #15 

Changes  - 
- Updated the credit section design and added the missing "Ideación y responsable
Iolanda Pensa" 

Steps to test - 
- See the bottom of website , changes will display there.

ScreenShot - 
Updated_footer

### CODE REVIEW

**Review by SannitaSSJ — CHANGES_REQUESTED** [review]
I would like you to correct the following:

1. Remove the additional whitespace before the name of the teachers in the "Agradecemos a las y los docentes:" section
2. Change the "Ideazione e responsabile" title section to "Concepción y responsabilidad"
3. Change the "Web design and data visualization:" title section to "Diseño web y visualización de datos"
4. Change the "Original project credits : " title section to "Créditos del proyecto original"

The rest looks good to me, and can be merged.

**Comment by Urmilasc** [comment]
Heyy @SannitaSSJ , Thank you for review !!

I get the 2, 3 & 4 points from the above , 

but not the 1 which is stating to remove the whitespaces before the teachers name , can you please clear it !!

**Comment by SannitaSSJ** [comment]
Sure. Code now looks like this:

```
									<p  class="mb-1">Ana Miranda </p>
									<p class="mb-1">	Annabel Castro</p>
									<p class="mb-1">Cecilia Torres</p>	
									<p class="mb-1">	Franco Salvetti</p>
									<p class="mb-1">	Iliana Trejos Cabrera</p>
									<p class="mb-1">	Marcelo Mónico</p>
									<p class="mb-1">Paula Olagüe Schettini</p>	
									<p class="mb-1">Romina Smith</p>	
```

It should look like this:

```
									<p  class="mb-1">Ana Miranda </p>
									<p class="mb-1">Annabel Castro</p>
									<p class="mb-1">Cecilia Torres</p>	
									<p class="mb-1">Franco Salvetti</p>
									<p class="mb-1">Iliana Trejos Cabrera</p>
									<p class="mb-1">Marcelo Mónico</p>
									<p class="mb-1">Paula Olagüe Schettini</p>	
									<p class="mb-1">Romina Smith</p>	
```

**Comment by Urmilasc** [comment]
Okay  , I try to find that one in the browser frontend

**Comment by Urmilasc** [comment]
Heyy @SannitaSSJ , I did the requested changes in the code .

Thankyou !!

**Review by SannitaSSJ — APPROVED** [review]

**Pull request merged**
